name: ljudcue
description: "Sound cue player"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  collection: ^1.16.0
  file_picker: ^8.0.3
  http: ^1.0.0
  path_provider: ^2.0.12
  provider: ^6.0.5

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_speed_dial: ^7.0.0
  path: ^1.9.0
  desktop_drop: ^0.4.4
  win32audio: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

msix_config:
  display_name: LjudCue
  app_installer: #<-- app installer configuration
   # publish_folder_path: c:\path\to\myPublishFolder
    hours_between_update_checks: 6
    automatic_background_task: false
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
  publisher_display_name: Linus Hvenfelt
  identity_name: com.linush.ljudcue
  msix_version: 1.0.0.0
  logo_path: ./assets/ljudcue.png
  capabilities: internetClient, backgroundMediaPlayback, globalMediaControl
